chore: comment out pre-push checks for prettier, build, and lint in husky script

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,19 +1,19 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-if ! npx prettier --write .; then
-  echo "Error: Code formatting failed. Please fix the issues before committing."
-  exit 1
-fi
+# if ! npx prettier --write .; then
+#   echo "Error: Code formatting failed. Please fix the issues before committing."
+#   exit 1
+# fi
 
-if ! npm run build; then
-  echo "Error: Code building failed. Please fix the issues before committing."
-  exit 1
-fi
+# if ! npm run build; then
+#   echo "Error: Code building failed. Please fix the issues before committing."
+#   exit 1
+# fi
 
-if ! npm run lint; then
-  echo "Error: Linting failed. Please fix the issues before committing."
-  exit 1
-fi
+# if ! npm run lint; then
+#   echo "Error: Linting failed. Please fix the issues before committing."
+#   exit 1
+# fi
 
 git pull origin develop
